### ISSUE TITLE
请问有持续更新的ios客户端嘛

### ISSUE THREAD

**Issue by Kazagask** [nonameShijian/noname#3]
## 问题描述
请问有持续更新的ios客户端嘛
## 问题信息

目前ios版本testflight的测试名额满了，从其他渠道找到的资源也是旧版本的（2020年之前），请问目前有持续更新的ios客户端嘛
## 检查清单

- [x] 此问题没有在其他issue(议题)中出现
- [ ] 我已将无名杀本体更新为最新版本
- [ ] 我已将所有扩展更新为最新版本
- [ ] 我填写了上面所有必要的信息

**Comment by nonameShijian** [comment]
没有。这个也不允许上架的

**Comment by Kazagask** [comment]
了解，请问testflight自签版本的作者目前还活跃嘛

**Comment by nonameShijian** [comment]
不认识
